import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ClerkProvider } from "@clerk/nextjs";

export const metaData = {
  title: "Car Rent Website Design",
  description: "Generated by Afaq ul Islam",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <title>AUI | Rental E-Commerce</title>
        </head>
        <body className={"text-[Plus Jakarta Sans]"}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
